[build]
builder = "dockerfile"

[deploy]
startCommand = "uvx --from langgraph-cli[inmem] --with-editable . --python 3.11 langgraph dev --host 0.0.0.0 --port $PORT --allow-blocking"
restartPolicyType = "always"
